WebApplication1/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLogic.Core;
using BusinessLogic.Core.ActionFilter;
using BusinessLogic.DBModel;
using BusinessLogic.DBModel.ArticleModel;
using BusinessLogic.DBModel.CartModel;
using System.Web.Helpers;
using System.Data.SqlClient;

namespace WebApplication1.Controllers
{
    public class ArticlesController : Controller
    {
        // GET: Articles
        public ActionResult Index(string articleAction = "")
        {
            UserRoleContext db = new UserRoleContext();

            string role = UserProperties.getRole();

            ViewBag.Role = role;

            if (articleAction == "deleted")
            {
                ViewBag.Action = "deleted";
            }

            if (role == "User")
            {
                var cartItems = db.cart_items.ToList();
                if (cartItems != null)
                {
                    ViewBag.CartItems = cartItems;
                }
            }

            return View(db.articles);
        }

        [AdminMod]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Article form, HttpPostedFileBase Image)
        {
            string articleImage = "default.png";

            if (Image != null)
            { 
                string fileName = Crypto.Hash(System.IO.Path.GetFileName(Image.FileName)) + ".png";
                string SaveLocation = Server.MapPath("~/Content/Articles/images/" + fileName);
                try
                {
                    Image.SaveAs(SaveLocation);
                    articleImage = fileName;
                }
                catch (Exception ex)
                {
                    Response.Write("Error: " + ex.Message);
                }
            }

            UserRoleContext db = new UserRoleContext();

            string articleText = form.Text;
            string articleTitle = form.Title;
            string articlePrice = form.Price;

            Article article = new Article
            {
                Text = articleText,
                Title = articleTitle,
                Image = articleImage,
                Price = articlePrice
            };

            db.articles.Add(article);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [AdminMod]
        public ActionResult Delete(int id)
        {
            UserRoleContext db = new UserRoleContext();

            var article = db.articles.Find(id);

            if (article != null)
            {
                // delete article
                db.articles.Remove(article);

                // delete article dependencies in CartItems table
                db.Database.ExecuteSqlCommand("DELETE FROM CartItems WHERE ArticleId=@id", 
                    new SqlParameter("@id", id));

                db.SaveChanges();
            }

            //return View("Index", db.articles);
            return RedirectToAction("Index", new { articleAction = "deleted" });
        }

        [UserMod]
        public ActionResult AddCart(int id)
        {
            UserRoleContext db = new UserRoleContext();

            int userId = UserProperties.getId();

            var articleId = id;

            CartItem cartItem = new CartItem { ArticleId = articleId, UserId = userId };

            db.cart_items.Add(cartItem);
            db.SaveChanges();

            var referer = Request.UrlReferrer.ToString();

            return Redirect(referer);
        }

        [AdminMod]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Article form, HttpPostedFileBase Image)
        {
            UserRoleContext db = new UserRoleContext();

            var articleImage = (from s in db.articles
                                where s.ID == form.ID
                                select s.Image).ToArray();

            if (Image != null)
            {
                string fileName = Crypto.Hash(System.IO.Path.GetFileName(Image.FileName)) + ".png";
                string SaveLocation = Server.MapPath("~/Content/Articles/images/" + fileName);
                try
                {
                    var result = db.articles.SingleOrDefault(b => b.ID == form.ID);
                    if (result != null)
                    {
                        result.Image = fileName;
                        db.SaveChanges();
                    }
                    Image.SaveAs(SaveLocation);
                    //articleImage = fileName;
                }
                catch (Exception ex)
                {
                    Response.Write("Error: " + ex.Message);
                }
            }

            var resultArticle = db.articles.SingleOrDefault(b => b.ID == form.ID);
            if (resultArticle != null)
            {
                resultArticle.Title = form.Title;
                resultArticle.Text = form.Text;
                resultArticle.Price = form.Price;
                db.SaveChanges();
            }

            var referer = Request.UrlReferrer.ToString();
            return RedirectToAction("Index", new { articleAction = "edited" });
        }
    }
}

WebApplication1/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLogic.Core;
using BusinessLogic.DBModel;

namespace WebApplication1.Controllers
{
    public class ContactUsController : Controller
    {
        // GET: ContactUs
        public ActionResult Index()
        {
            string role = UserProperties.getRole();
            ViewBag.Role = role;

            UserRoleContext db = new UserRoleContext();

            if (role == "User")
            {
                var cartItems = db.cart_items.ToList();
                if (cartItems != null)
                {
                    ViewBag.CartItems = cartItems;
                }
            }

            return View();
        }
    }
}

WebApplication1/Controllers/LogOutController.cs
using System;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class LogOutController : Controller
    {
        // GET: LogOut
        public ActionResult Index()
        {
            if (Request.Cookies["UserData"] != null)
            {
                HttpCookie cookie = new HttpCookie("UserData");
                cookie.Expires = DateTime.Now.AddYears(-1);
                Response.Cookies.Add(cookie);
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

WebApplication1/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.SessionState;
using BusinessLogic;
using BusinessLogic.Interfaces;
using WebApplication1.Models;
using Domain.Entities.User;
using BusinessLogic.DBModel;
using UserRole = BusinessLogic.Core.UserRole;
using BusinessLogic.Core;

namespace WebApplication1.Controllers
{
    public class LoginController : Controller
    {
        //private UserContext db = new UserContext();
        private readonly ISession _session;

        public LoginController()
        {
            var bl = new MyBusinessLogic();
            _session = bl.GetSessionBL();
        }

        //GET: Login
        public ActionResult Index()
        {
            string role = UserProperties.getRole();
            ViewBag.Role = role;

            UserRoleContext db = new UserRoleContext();

            if (role == "User")
            {
                var cartItems = db.cart_items.ToList();
                if (cartItems != null)
                {
                    ViewBag.CartItems = cartItems;
                }
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(UserLogin login)
        {
            if (ModelState.IsValid)
            {
                ULoginData data = new ULoginData
                {
                    Email = login.Email,
                    Password = login.Password,
                    LoginIp = Request.UserHostAddress,
                    LoginDateTime = DateTime.Now
                };
                var userLogin = _session.UserLogin(data);
                
                if (userLogin.Status)
                {
                    //ADD COOKIE
                    HttpCookie cookie = new HttpCookie("UserData");
                    cookie["UserName"] = userLogin.UserName;
                    cookie["UserId"] = userLogin.ID.ToString();
                    cookie.Expires = DateTime.Now.AddMonths(1);
                    Response.Cookies.Add(cookie);

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", userLogin.StatusMsg);
                    ViewBag.Message = userLogin.StatusMsg;
                    return View();
                }
            }

            return View();
        }
    }
}

WebApplication1/Views/Shared/_Footer.cshtml
<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 2021 Lîjeico Ilie</p>
        <p class="m-0 text-center text-white">skatervan@gmail.com</p>
    </div>
    <!-- /.container -->
</footer>

WebApplication1/Views/Shared/_Header.cshtml
@using BusinessLogic.Core;
@{
    var role = UserProperties.getRole();

    var userCartItems = UserProperties.getCart();
}

@{
    var cartCount = 0;
    if (ViewBag.CartItems != null)
    {
        cartCount = userCartItems.Count;
    }
}

@{
    if (role == "User")
    {
        <!-- Modal Show User Cart-->
        <div class="modal fade" id="cartModal" role="dialog">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header justify-content-center">
                        <h4 class="modal-title">Cosul meu</h4>
                    </div>
                    <div class="modal-body">
                        @{ 
                            float totalPrice = 0;
                            foreach (BusinessLogic.DBModel.CartModel.UserCartItem item in userCartItems)
                            {
                                totalPrice += item.Price.AsFloat();
                                <div class="card mb-3">
                                    <div class="row no-gutters">
                                        <div class="col-md-4">
                                            <img style="height:100%;" src="~/Content/Articles/images/@item.Image" class="card-img" alt="Cart Item Image">
                                        </div>
                                        <div class="col-md-8">
                                            <div class="card-body">
                                                <h5 class="card-title">@item.Title</h5>
                                                <p class="card-text">@item.Text</p>
                                                <p class="card-text"><small class="text-muted">Added to cart on: @item.Datetime</small></p>
                                                <p class="card-text"><big style="color:darkred;">$ @item.Price</big></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <div class="row">
                            @{
                                if (totalPrice > 0)
                                {
                                    <span style="margin-right:3rem;align-self:center;color:darkred;font-size:x-large">Total: $@totalPrice</span>
                                }
                            }
                            <button type="submit" class="btn btn-primary" id="add-article" data-dismiss="modal">Achită</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
}

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="@Url.Action("Index", "Home")">InfoTechnologies</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                @{
                    if (ViewBag.Role == "Admin")
                    {
                        <li class="nav-item @*active*@">
                            <a class="nav-link" href="@Url.Action("Index", "Admin")">Admin Panel</a>
                        </li>
                    }
                }
                <li class="nav-item @*active*@">
                    <a class="nav-link" href="javascript:void(0);">Rolul: @ViewBag.Role</a>
                </li>
                <li class="nav-item @*active*@">
                    <a class="nav-link" href="@Url.Action("Index", "Articles")">Articole</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "ContactUs")">Contacteaza-ne</a>
                </li>
                @{
                    if (UserProperties.getUser() != null)
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="javascript:void(0);" role="button" aria-haspopup="true" aria-expanded="false">Profile</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="javascript:void(0);">@UserProperties.getUser().LastName</a>
                                @if (role == "User")
                                {
                                    <a class="dropdown-item" href="javascript:void(0);" data-toggle="modal" data-target="#cartModal">Cart <span class="badge badge-success">@cartCount</span></a>
                                }
                                <a class="dropdown-item" href="@Url.Action("Index", "LogOut")">Log Out</a>
                            </div>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Login")">Log In</a>
                        </li>
                    }
                }
            </ul>
        </div>
    </div>
</nav>

WebApplication1/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Internet Magazin | @ViewBag.Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @*<link rel="stylesheet" href="~/layouts/bootstrap4/css/bootstrap.min.css">*@
    <script src="~/layouts/jquery/jquery-3.4.1.min.js"></script>
    <script src="~/layouts/bootstrap4/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous"></script>
    @*<link rel="stylesheet" type="text/css" href="~/layouts/css/style.css">*@
    <script src="~/layouts/js/nav-pages/main.js" type="text/javascript"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900"
          rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
    @Styles.Render("~/bundles/custom/css")
    @Styles.Render("~/bundles/bootstrap/css")
    @*<link rel="stylesheet" type="text/css" href="~/layouts/css/nav-pages/log-in.css">*@
</head>
<body>
    @Html.Partial("_Header")

    <!-- Page Content -->
    <div class="container">
        @RenderBody()
    </div>
    <!-- /.container -->

    @Html.Partial("_Footer")

    @RenderSection("scripts", required: false)
</body>
</html>