WebApplication1/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.SessionState;
using BusinessLogic;
using BusinessLogic.Interfaces;
using WebApplication1.Models;
using Domain.Entities.User;
using BusinessLogic.DBModel;
using UserRole = BusinessLogic.Core.UserRole;
using BusinessLogic.Core;

namespace WebApplication1.Controllers
{
    public class LoginController : Controller
    {
        //private UserContext db = new UserContext();
        private readonly ISession _session;

        public LoginController()
        {
            var bl = new MyBusinessLogic();
            _session = bl.GetSessionBL();
        }

        //GET: Login
        public ActionResult Index()
        {
            string role = UserProperties.getRole();
            ViewBag.Role = role;

            UserRoleContext db = new UserRoleContext();

            if (role == "User")
            {
                var cartItems = db.cart_items.ToList();
                if (cartItems != null)
                {
                    ViewBag.CartItems = cartItems;
                }
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(UserLogin login)
        {
            if (ModelState.IsValid)
            {
                ULoginData data = new ULoginData
                {
                    Email = login.Email,
                    Password = login.Password,
                    LoginIp = Request.UserHostAddress,
                    LoginDateTime = DateTime.Now
                };
                var userLogin = _session.UserLogin(data);
                
                if (userLogin.Status)
                {
                    //ADD COOKIE
                    HttpCookie cookie = new HttpCookie("UserData");
                    cookie["UserName"] = userLogin.UserName;
                    cookie["UserId"] = userLogin.ID.ToString();
                    cookie.Expires = DateTime.Now.AddMonths(1);
                    Response.Cookies.Add(cookie);

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", userLogin.StatusMsg);
                    ViewBag.Message = userLogin.StatusMsg;
                    return View();
                }
            }

            return View();
        }
    }
}

WebApplication1/Controllers/PassRecoverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLogic.Core;
using BusinessLogic.DBModel;

namespace WebApplication1.Controllers
{
    public class PassRecoverController : Controller
    {
        // GET: PassRecover
        public ActionResult Index()
        {
            string role = UserProperties.getRole();
            ViewBag.Role = role;

            UserRoleContext db = new UserRoleContext();

            if (role == "User")
            {
                var cartItems = db.cart_items.ToList();
                if (cartItems != null)
                {
                    ViewBag.CartItems = cartItems;
                }
            }

            return View();
        }
    }
}

WebApplication1/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLogic;
using BusinessLogic.Core;
using BusinessLogic.DBModel;
using BusinessLogic.Interfaces;
using Domain.Entities.User;

namespace WebApplication1.Controllers
{
    public class RegistrationController : Controller
    {
        private readonly ISession _session;

        public RegistrationController()
        {
            var bl = new MyBusinessLogic();
            _session = bl.GetSessionBL();
        }

        UserContext db = new UserContext();

        // GET: Registration
        public ActionResult Index()
        {
            string role = UserProperties.getRole();
            ViewBag.Role = role;

            UserRoleContext db = new UserRoleContext();

            if (role == "User")
            {
                var cartItems = db.cart_items.ToList();
                if (cartItems != null)
                {
                    ViewBag.CartItems = cartItems;
                }
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(URegistrationData data)
        {
            if (ModelState.IsValid)
            {
                var userRegistration = _session.UserRegistration(data);

                /*if (userRegistration.Status)
                {
                }
                else
                {
                    ModelState.AddModelError("", userRegistration.StatusMsg);
                    ViewBag.Message = userRegistration.StatusMsg;
                }#1#*/

                ViewBag.Status = userRegistration.Status;
                ViewBag.Message = userRegistration.StatusMsg;
            }


            return View();
        }
    }
}

WebApplication1/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var message = ViewBag.Message;
}

@using System.Web.Optimization

<div class="login-form card col-sm-4">
    <article class="card-body">
        <h4 class="card-title text-center mb-4 mt-1">Sign in</h4>
        <hr>
        @{
            if (message != "")
            {
                <p class="text-danger text-center">@message</p>
            }
        }

        <form method="post" action="/login/index">
            @Html.AntiForgeryToken()
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                    </div>
                    <input name="Email" class="form-control" placeholder="Email or login" type="email" required>
                </div> <!-- input-group.// -->
            </div> <!-- form-group// -->
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                    </div>
                    <input name="Password" class="form-control" placeholder="******" type="password">
                </div> <!-- input-group.// -->
            </div> <!-- form-group// -->
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block"> Login </button>
            </div> <!-- form-group// -->
            <p class="text-center"><a href="@Url.Action("Index", "PassRecover")">Forgot password?</a></p>
            <p class="text-center">Already have an account? <a href="@Url.Action("Index", "Registration")">Sign up</a></p>
        </form>
    </article>
</div> <!-- card.// -->